Added scripts

diff --git a/bash_to_python/tp_chained_tp_rdb_hdb_starter b/bash_to_python/tp_chained_tp_rdb_hdb_starter
--- a/bash_to_python/tp_chained_tp_rdb_hdb_starter
+++ b/bash_to_python/tp_chained_tp_rdb_hdb_starter
@@ -6,7 +6,7 @@
 set -e
 
 echo
-echo "****************************Started script tickerplant_rdb_hdb_starter****************************"
+echo "****************************Started script tp_chained_tp_rdb_hdb_starter****************************"
 
 
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
@@ -22,7 +22,7 @@ fi
 
 source .venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
 
-python -m tick_architecture.tickerplant_rdb_hdb_starter "$DB_DIR" "$LOGS_DIR" || { echo "Python script failed"; exit 1; }
+python -m tick_architecture.tp_chained_tp_rdb_hdb_starter "$DB_DIR" "$LOGS_DIR" || { echo "Python script failed"; exit 1; }
 
 echo
-echo "****************************Ended script tickerplant_rdb_hdb_starter successfully****************************"
+echo "****************************Ended script tp_chained_tp_rdb_hdb_starter successfully****************************"
